{
 "title": "Sangfor AD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "virtualService",
    "query": {
     "query": "label_values(ad_client_connection{pathName=\"virtual-service\"},name)"
    }
   },
   {
    "name": "currentService",
    "query": {
     "query": "label_values(ad_connection{pathName=\"current-version\"},name)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(ad_connection{pathName=\"pool\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU & 内存 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ad_cpu_usage{pathName=\"system\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ad_memory_usage{pathName=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU and Disk 温度",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "ad_temperature{pathName=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "ad_speed{pathName=\"system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "虚拟服务", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "http qps",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ad_http_request_rate{name =~\"$virtualService\",pathName=\"virtual-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "http 总请求数",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "ad_total_http_request{name =~\"$virtualService\",pathName=\"virtual-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "并发连接数 established",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ad_connection_established{name =~\"$virtualService\",pathName=\"virtual-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "客户端连接数",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ad_client_connection{name =~\"$virtualService\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ad_connection{name =~\"$virtualService\" ,pathName=\"virtual-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "节点池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "流量",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ad_upstream_throughput{name=~\"$pool\",pathName=\"pool\"}",
     "legendFormat": "{{name}}-up"
    },
    {
     "expr": "ad_downstream_throughput{name=~\"$pool\",pathName=\"pool\"}",
     "legendFormat": "{{name}}-down"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "ad_connection{name =~\"$pool\" ,pathName=\"pool\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "http qps",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "ad_http_request_rate{name =~\"$pool\",pathName=\"pool\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "业务主机", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "流量",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ad_upstream_throughput{name=~\"$currentService\",pathName=\"current-version\"}",
     "legendFormat": "{{name}}-up"
    },
    {
     "expr": "ad_downstream_throughput{name=~\"$currentService\",pathName=\"current-version\"}",
     "legendFormat": "{{name}}-down"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "ad_connection{name =~\"$currentService\" ,pathName=\"current-version\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "http qps",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "ad_http_request_rate{name=~\"$currentService\",pathName=\"current-version\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}